export const menuItems = [
  {
    id: 1,
    path: '/',
    size: '32',
    iconName: 'humbleicons:home',
    title: 'Home',
  },
  {
    id: 2,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 3,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 4,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 5,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 6,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 7,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 8,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 9,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 10,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
  {
    id: 11,
    path: '/explore',
    size: '30',
    iconName: 'ic:sharp-search',
    title: 'Exprore',
  },
]
